$OU = "ou=staff,OU=employees,DC=domain,DC=local" # OU you want to filter/export
$CSVname = "c:\scripts\active_directory\CurrentStaff.csv" #Name and location of the export file

Import-Module ActiveDirectory #Imports AD module

#This search will give you Office field, Lastname, Firstname, and email address
Get-ADUser -SearchBase $OU -Filter * -Properties Displayname,EmailAddress| Select DisplayName,EmailAddress | Export-Csv $csvname

# Properties * will return all fields 
# Common properties, SamAccountName, Email, DisplayName, Surname, EmailAddress,
# Full list of properties that can be searched:
#AccountExpirationDate	
#accountExpires	
#AccountLockoutTime	
#AccountNotDelegated	
#AllowReversiblePasswordEncryption	
#AuthenticationPolicy	
#AuthenticationPolicySilo	
#BadLogonCount	
#badPasswordTime	
#badPwdCount	
#CannotChangePassword	
#CanonicalName	
#Certificates	
#City	
#CN	
#codePage	
#Company	
#CompoundIdentitySupported	
#Country	
#countryCode	
#Created	
#createTimeStamp	
#Deleted	
#Department	
#Description	
#DisplayName	
#DistinguishedName	
#Division	
#DoesNotRequirePreAuth	
#dSCorePropagationData	
#EmailAddress	
#EmployeeID	
#EmployeeNumber	
#Enabled	
#Fax	
#GivenName	
#HomeDirectory	
#HomedirRequired	
#HomeDrive	
#HomePage	
#HomePhone	
#Initials	
#instanceType	
#isDeleted	
#KerberosEncryptionType	
#LastBadPasswordAttempt	
#LastKnownParent	
#lastLogoff	
#lastLogon	
#LastLogonDate	
#lastLogonTimestamp	
#LockedOut	
#lockoutTime	
#logonCount	
#LogonWorkstations	
#Manager	
#MemberOf	
#MNSLogonAccount	
#MobilePhone	
#Modified	
#modifyTimeStamp	
#msDS-PSOApplied
#msDS-User-Account-Control-Computed	
#Name	
#nTSecurityDescriptor	
#ObjectCategory	
#ObjectClass	
#ObjectGUID	
#objectSid	
#Office	
#OfficePhone	
#Organization	
#OtherName	
#PasswordExpired	
#PasswordLastSet	
#PasswordNeverExpires	
#PasswordNotRequired	
#POBox	
#PostalCode	
#PrimaryGroup	
#primaryGroupID	
#PrincipalsAllowedToDelegateToAccount	
#ProfilePath
#ProtectedFromAccidentalDeletion	
#pwdLastSet	
#SamAccountName	
#sAMAccountType	
#ScriptPath	
#sDRightsEffective	
#ServicePrincipalNames	
#SID	
#SIDHistory	
#SmartcardLogonRequired	
#sn	
#State	
#StreetAddress	
#Surname	
#Title	
#TrustedForDelegation	
#TrustedToAuthForDelegation	
#UseDESKeyOnly	
#userAccountControl	
#userCertificate	
#UserPrincipalName	
#uSNChanged	
#uSNCreated	
#whenChanged
#whenCreated	
#PropertyNames	
#AddedProperties	
#RemovedProperties	
#ModifiedProperties	
#PropertyCount
